"""
Build a more reasonable grid-to-grid travel cost table using shortest paths on the
directional grid graph generated by stage06.

This is separate from the main pipeline and does not modify existing outputs.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import shortest_path


def parse_args():
    parser = argparse.ArgumentParser(description="Generate improved travel costs from an existing version.")
    parser.add_argument("--version-id", default="raw_rebuild_validation")
    parser.add_argument("--output-dir", default="data_work/outputs")
    parser.add_argument("--paper-dir", default="Documents/todo_outputs")
    parser.add_argument("--grid-type", default="square", choices=["square", "hex", "voronoi"])
    parser.add_argument("--period", default="AM", choices=["AM", "PM"])
    return parser.parse_args()


def build_shortest_path_costs(version_root: Path, grid_type: str, period: str, paper_dir: Path):
    data_dir = version_root / "data"
    edges = pd.read_csv(data_dir / f"t_edges_{grid_type}_{period}.csv")
    od = pd.read_csv(data_dir / f"OD_{grid_type}_reachable_{period}.csv")
    t_nodes = pd.read_csv(data_dir / f"t_nodes_{grid_type}.csv")
    grid = gpd.read_parquet(data_dir / f"grid_{grid_type}_master.parquet")

    edges["t_min"] = pd.to_numeric(edges["t_min"], errors="coerce")
    edges = edges.loc[edges["t_min"].notna() & np.isfinite(edges["t_min"]) & (edges["t_min"] > 0)].copy()
    n = int(max(edges["i"].max(), edges["j"].max()) + 1)
    graph = coo_matrix((edges["t_min"].values, (edges["i"].values, edges["j"].values)), shape=(n, n)).tocsr()
    dist = shortest_path(graph, directed=True, unweighted=False)

    grid = grid[["grid_id", "geometry"]].copy()
    if grid.crs is None:
        raise ValueError("Grid CRS missing")
    grid_3857 = grid.to_crs(3857)
    centroids = grid_3857.geometry.centroid
    grid_3857["cx"] = centroids.x
    grid_3857["cy"] = centroids.y
    node_xy = t_nodes.merge(grid_3857.drop(columns="geometry"), on="grid_id", how="left")

    od2 = od.merge(t_nodes.rename(columns={"node_i": "home_tnode"}), left_on="home_grid", right_on="grid_id", how="left").drop(columns=["grid_id"])
    od2 = od2.merge(t_nodes.rename(columns={"grid_id": "work_grid_ref", "node_i": "work_tnode"}), left_on="work_grid", right_on="work_grid_ref", how="left").drop(columns=["work_grid_ref"])
    od2 = od2.dropna(subset=["home_tnode", "work_tnode"]).copy()
    od2["home_tnode"] = od2["home_tnode"].astype(int)
    od2["work_tnode"] = od2["work_tnode"].astype(int)
    od2["travel_time_min"] = dist[od2["home_tnode"].values, od2["work_tnode"].values]
    od2.loc[~np.isfinite(od2["travel_time_min"]), "travel_time_min"] = np.nan

    home_xy = node_xy.rename(columns={"grid_id": "home_grid", "cx": "home_cx", "cy": "home_cy"})
    work_xy = node_xy.rename(columns={"grid_id": "work_grid", "cx": "work_cx", "cy": "work_cy"})
    od2 = od2.merge(home_xy[["home_grid", "home_cx", "home_cy"]], on="home_grid", how="left")
    od2 = od2.merge(work_xy[["work_grid", "work_cx", "work_cy"]], on="work_grid", how="left")
    od2["euclid_dist_km"] = np.sqrt((od2["home_cx"] - od2["work_cx"]) ** 2 + (od2["home_cy"] - od2["work_cy"]) ** 2) / 1000.0
    od2["effective_speed_kmh"] = np.where(
        od2["travel_time_min"] > 0,
        od2["euclid_dist_km"] / (od2["travel_time_min"] / 60.0),
        np.nan,
    )

    valid = od2.loc[od2["travel_time_min"].notna() & np.isfinite(od2["travel_time_min"]) & (od2["travel_time_min"] > 0)].copy()

    summary = pd.DataFrame(
        [
            {
                "grid_type": grid_type,
                "period": period,
                "reachable_od_pairs": int(len(od2)),
                "valid_cost_pairs": int(len(valid)),
                "weighted_avg_travel_time_min": float(np.average(valid["travel_time_min"], weights=valid["pop"])) if len(valid) else np.nan,
                "weighted_median_travel_time_min": float(valid.loc[valid["pop"] > 0, "travel_time_min"].median()) if len(valid) else np.nan,
                "weighted_avg_euclid_dist_km": float(np.average(valid["euclid_dist_km"], weights=valid["pop"])) if len(valid) else np.nan,
                "weighted_avg_effective_speed_kmh": float(np.average(valid["effective_speed_kmh"], weights=valid["pop"])) if len(valid) else np.nan,
            }
        ]
    )

    out_data = paper_dir / "data"
    out_data.mkdir(parents=True, exist_ok=True)
    od_path = out_data / f"od_{grid_type}_{period.lower()}_shortest_path_costs.csv"
    summary_path = out_data / f"od_{grid_type}_{period.lower()}_shortest_path_summary.csv"
    od2.to_csv(od_path, index=False)
    summary.to_csv(summary_path, index=False)
    print(od_path)
    print(summary_path)


def main():
    args = parse_args()
    version_root = Path(args.output_dir) / args.version_id
    paper_dir = Path(args.paper_dir)
    build_shortest_path_costs(version_root, args.grid_type, args.period, paper_dir)


if __name__ == "__main__":
    main()
